name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: dotnet build Elsa.Samples.sln -c Release -o out
    - name: Test
      run: dotnet test Elsa.Samples.sln --no-build --verbosity normal

    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 
       with:
          heroku_api_key: 4c9cf8ab-4f81-47ba-9978-632084dec73d
          heroku_app_name: "devtest123321" 
          heroku_email: "quangdung1996.97@gmail.com"
